format long
% =============================================================================================================================
% Glavno okno
glavnoOkno = uifigure("Position", [700, 700, 400, 400], Name="Izris Beziereve krivulje");
steviloTockLabel = uilabel(glavnoOkno, Text="Vnesite število točk: ", Position=[30, 330, 200, 30]);
steviloTock = uieditfield(glavnoOkno, "numeric", "Position", [30, 300, 200, 30]);
steviloTock.Limits = [2, 20];
korakParametraLabel = uilabel(glavnoOkno, Text="Vnesite korak parametra: ", Position=[30, 270, 200, 30]);
korakParametra = uieditfield(glavnoOkno, "numeric", "Position", [30, 240, 200, 30]);
korakParametra.Limits = [1, 1000];
poligonCheckBox = uicheckbox(glavnoOkno, "Text", "Prikaži kontrolni poligon", "Value", 0, "Position", [30, 200, 200, 30]);
izrisButton = uibutton(glavnoOkno,"push", ...
    "Text","Izberi točke in izriši", ...
    "BackgroundColor", [0.74, 0.83, 0.90], ...
    "Position",[30 150 150 30], ...
    "ButtonPushedFcn", @(src, event) izrisi(steviloTock.Value, korakParametra.Value, poligonCheckBox.Value));
zapustiButton = uibutton(glavnoOkno,"push", ...
    "Text","Zapri", ...
    "BackgroundColor", [0.96, 0.76, 0.76], ...
    "Position",[190 150 60 30], ...
    "ButtonPushedFcn", @(src, event) close(glavnoOkno));
% =============================================================================================================================
